"""add an orders table with a link to all tables

Revision ID: 283cc4f4fa00
Revises: 3b9ff5e239ae
Create Date: 2021-09-21 09:38:47.274014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283cc4f4fa00'
down_revision = '3b9ff5e239ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['toppings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
