"""created a password and email field

Revision ID: 89f4dc05aba7
Revises: 283cc4f4fa00
Create Date: 2021-09-21 11:26:20.936941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f4dc05aba7'
down_revision = '283cc4f4fa00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
