"""changed names of orders column

Revision ID: f8271e0617af
Revises: 89f4dc05aba7
Create Date: 2021-09-21 11:38:27.437805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8271e0617af'
down_revision = '89f4dc05aba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pizza_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('size_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('topping_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_role_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'toppings', ['topping_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'size', ['size_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'pizza', ['pizza_id'], ['id'])
    op.drop_column('orders', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_role_id_fkey', 'orders', 'toppings', ['role_id'], ['id'])
    op.drop_column('orders', 'topping_id')
    op.drop_column('orders', 'size_id')
    op.drop_column('orders', 'pizza_id')
    # ### end Alembic commands ###
